'use client'

import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { 
  ArrowLeft,
  Shield,
  CheckCircle,
  AlertCircle,
  Copy,
  ExternalLink,
  Search,
  Loader2
} from 'lucide-react'
import { useWallet } from '@/lib/aleo-wallet-provider'

interface ProofVerification {
  hash: string
  status: 'verified' | 'invalid' | 'not_found'
  timestamp: string
  blockHeight: number
  transactionId: string
  analysisType: string
  resultHash: string
  publicInputs: string[]
}

function VerifyProofContent() {
  const { connected } = useWallet()
  const router = useRouter()
  const searchParams = useSearchParams()
  const [proofHash, setProofHash] = useState('')
  const [verifying, setVerifying] = useState(false)
  const [verification, setVerification] = useState<ProofVerification | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const hashFromUrl = searchParams.get('hash')
    if (hashFromUrl) {
      setProofHash(hashFromUrl)
      handleVerify(hashFromUrl)
    }
  }, [searchParams])

  const handleVerify = async (hash?: string) => {
    const hashToVerify = hash || proofHash
    if (!hashToVerify.trim()) return

    setVerifying(true)
    setError(null)
    setVerification(null)

    try {
      // Simulate verification process
      await new Promise(resolve => setTimeout(resolve, 2000))

      // Mock verification result
      const mockVerification: ProofVerification = {
        hash: hashToVerify,
        status: 'verified',
        timestamp: new Date().toISOString(),
        blockHeight: Math.floor(Math.random() * 1000000) + 500000,
        transactionId: '0x' + Array.from({length: 64}, () => Math.floor(Math.random() * 16).toString(16)).join(''),
        analysisType: 'Document Risk Assessment',
        resultHash: '0x' + Array.from({length: 64}, () => Math.floor(Math.random() * 16).toString(16)).join(''),
        publicInputs: [
          'analysis_type: document_risk',
          'confidence_score: 85',
          'timestamp: ' + Math.floor(Date.now() / 1000),
          'user_address: ' + (connected ? 'aleo1...' : 'anonymous')
        ]
      }

      setVerification(mockVerification)
    } catch (err) {
      setError('Failed to verify proof. Please check the hash and try again.')
    } finally {
      setVerifying(false)
    }
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
  }

  const formatDate = (timestamp: string) => {
    return new Date(timestamp).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    })
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border/40">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <Button variant="ghost" size="sm" onClick={() => router.push('/')}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            <div className="flex items-center space-x-2">
              <img src="/veilnet-logo.png" alt="VeilNet AI" className="h-6 w-6 object-contain" />
              <span className="text-xl font-bold">VeilNet AI</span>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Page Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold mb-2">Proof Verification</h1>
            <p className="text-muted-foreground">
              Verify zero-knowledge proofs generated by VeilNet AI analysis on the Aleo blockchain.
            </p>
          </div>

          {/* Verification Input */}
          <Card className="mb-8">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Search className="h-5 w-5 mr-2" />
                Enter Proof Hash
              </CardTitle>
              <CardDescription>
                Paste the proof hash from your analysis results to verify its authenticity on the blockchain.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex space-x-2">
                  <Input
                    placeholder="0x1a2b3c4d5e6f7890abcdef..."
                    value={proofHash}
                    onChange={(e) => setProofHash(e.target.value)}
                    className="font-mono"
                    disabled={verifying}
                  />
                  <Button 
                    onClick={() => handleVerify()}
                    disabled={!proofHash.trim() || verifying}
                  >
                    {verifying ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Verifying...
                      </>
                    ) : (
                      <>
                        <Shield className="h-4 w-4 mr-2" />
                        Verify
                      </>
                    )}
                  </Button>
                </div>
                
                <p className="text-sm text-muted-foreground">
                  Proof hashes are 64-character hexadecimal strings starting with "0x"
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Error Display */}
          {error && (
            <Alert variant="destructive" className="mb-8">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {/* Verification Results */}
          {verification && (
            <div className="space-y-6">
              {/* Status Card */}
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center">
                      {verification.status === 'verified' ? (
                        <CheckCircle className="h-6 w-6 mr-2 text-green-500" />
                      ) : (
                        <AlertCircle className="h-6 w-6 mr-2 text-red-500" />
                      )}
                      Proof {verification.status === 'verified' ? 'Verified' : 'Invalid'}
                    </CardTitle>
                    <Badge 
                      variant={verification.status === 'verified' ? 'default' : 'destructive'}
                      className="text-xs"
                    >
                      {verification.status.toUpperCase()}
                    </Badge>
                  </div>
                  <CardDescription>
                    {verification.status === 'verified' 
                      ? 'This proof has been successfully verified on the Aleo blockchain.'
                      : 'This proof could not be verified or does not exist on the blockchain.'
                    }
                  </CardDescription>
                </CardHeader>
              </Card>

              {verification.status === 'verified' && (
                <>
                  {/* Proof Details */}
                  <Card>
                    <CardHeader>
                      <CardTitle>Proof Details</CardTitle>
                      <CardDescription>
                        Cryptographic proof information stored on the Aleo blockchain.
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="grid md:grid-cols-2 gap-4">
                        <div>
                          <h4 className="font-medium mb-2">Analysis Type</h4>
                          <p className="text-muted-foreground">{verification.analysisType}</p>
                        </div>
                        <div>
                          <h4 className="font-medium mb-2">Verification Time</h4>
                          <p className="text-muted-foreground">{formatDate(verification.timestamp)}</p>
                        </div>
                        <div>
                          <h4 className="font-medium mb-2">Block Height</h4>
                          <p className="text-muted-foreground font-mono">{verification.blockHeight.toLocaleString()}</p>
                        </div>
                        <div>
                          <h4 className="font-medium mb-2">Transaction ID</h4>
                          <div className="flex items-center space-x-2">
                            <p className="text-muted-foreground font-mono text-sm truncate">
                              {verification.transactionId}
                            </p>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => copyToClipboard(verification.transactionId)}
                            >
                              <Copy className="h-4 w-4" />
                            </Button>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Proof Hash */}
                  <Card>
                    <CardHeader>
                      <CardTitle>Proof Hash</CardTitle>
                      <CardDescription>
                        The unique identifier for this zero-knowledge proof.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="bg-muted p-4 rounded-lg">
                        <div className="flex items-center justify-between">
                          <p className="font-mono text-sm break-all pr-4">{verification.hash}</p>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => copyToClipboard(verification.hash)}
                          >
                            <Copy className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Result Hash */}
                  <Card>
                    <CardHeader>
                      <CardTitle>Result Hash</CardTitle>
                      <CardDescription>
                        Cryptographic hash of the analysis results without revealing the actual data.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="bg-muted p-4 rounded-lg">
                        <div className="flex items-center justify-between">
                          <p className="font-mono text-sm break-all pr-4">{verification.resultHash}</p>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => copyToClipboard(verification.resultHash)}
                          >
                            <Copy className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Public Inputs */}
                  <Card>
                    <CardHeader>
                      <CardTitle>Public Inputs</CardTitle>
                      <CardDescription>
                        Non-sensitive information that was used to generate this proof.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2">
                        {verification.publicInputs.map((input, index) => (
                          <div key={index} className="bg-muted p-3 rounded-lg">
                            <p className="font-mono text-sm">{input}</p>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>

                  {/* Actions */}
                  <div className="flex space-x-4">
                    <Button variant="outline">
                      <ExternalLink className="h-4 w-4 mr-2" />
                      View on Aleo Explorer
                    </Button>
                    <Button variant="outline" onClick={() => router.push('/results')}>
                      View All Results
                    </Button>
                  </div>
                </>
              )}
            </div>
          )}

          {/* How It Works */}
          <Card className="mt-12">
            <CardHeader>
              <CardTitle>How Proof Verification Works</CardTitle>
              <CardDescription>
                Understanding VeilNet's zero-knowledge proof system.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid md:grid-cols-3 gap-6">
                <div className="text-center">
                  <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <Shield className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="font-semibold mb-2">Zero-Knowledge Proof</h3>
                  <p className="text-sm text-muted-foreground">
                    Proves computation was performed correctly without revealing input data.
                  </p>
                </div>
                
                <div className="text-center">
                  <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <CheckCircle className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="font-semibold mb-2">Blockchain Verification</h3>
                  <p className="text-sm text-muted-foreground">
                    Proofs are stored on Aleo blockchain for immutable verification.
                  </p>
                </div>
                
                <div className="text-center">
                  <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <ExternalLink className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="font-semibold mb-2">Public Auditability</h3>
                  <p className="text-sm text-muted-foreground">
                    Anyone can verify proofs independently without accessing private data.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

export default function VerifyProofPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4" />
          <p className="text-muted-foreground">Loading proof verification...</p>
        </div>
      </div>
    }>
      <VerifyProofContent />
    </Suspense>
  )
}